# Generated by Django 2.0.10 on 2019-02-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('total_time', models.CharField(max_length=255, verbose_name='Tiempo total')),
            ],
            options={
                'verbose_name': 'Experiencia',
            },
        ),
    ]
