# Generated by Django 2.0.10 on 2019-02-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/experiences', verbose_name='Imagen')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experiences.Experiences', verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Imagen',
            },
        ),
        migrations.CreateModel(
            name='ExperiencesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='experiences.Experiences', verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
    ]
