# Generated by Django 2.0.10 on 2019-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_auto_20190206_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
