# Generated by Django 2.0.10 on 2019-02-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experiences_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencesOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255, verbose_name='Opcion')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Opcion de la experiencia',
                'verbose_name_plural': 'Opciones de la experiencia',
            },
        ),
        migrations.AddField(
            model_name='experiences',
            name='short_description',
            field=models.CharField(default='', max_length=255, verbose_name='Descripcion corta'),
        ),
        migrations.AddField(
            model_name='experiencesoption',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_options', to='experiences.Experiences', verbose_name='Experience'),
        ),
    ]
