# Generated by Django 2.0.10 on 2019-01-21 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del anuncio')),
                ('code', models.CharField(max_length=255, verbose_name='Código del anuncio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='RoomItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/rooms', verbose_name='Logo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='rooms.Room', verbose_name='Habitacion')),
            ],
            options={
                'verbose_name': 'Item de la habitacion',
                'verbose_name_plural': 'Items de la habitacion',
            },
        ),
    ]
