# Generated by Django 2.0.10 on 2019-01-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomitems',
            name='logo',
            field=models.FileField(upload_to='logos/rooms', verbose_name='Logo'),
        ),
    ]
