# Generated by Django 2.0.10 on 2019-01-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='TEST', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
