# Generated by Django 2.0.10 on 2019-01-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_categories', to='rooms.Category', verbose_name='Tipo de acomodacion'),
        ),
    ]
