# Generated by Django 2.0.10 on 2019-01-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20190124_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/rooms', verbose_name='Imagen')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_images', to='rooms.Room', verbose_name='Habitacion')),
            ],
            options={
                'verbose_name': 'Imagen de la habitacion',
                'verbose_name_plural': 'Imagenes de la habitacion',
            },
        ),
    ]
