# Generated by Django 2.0.10 on 2019-01-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_description',
            field=models.CharField(default='', max_length=255, verbose_name='Descripcion Corta'),
        ),
    ]
