# Generated by Django 2.0.10 on 2019-01-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio de la habitacion'),
        ),
    ]
