# Generated by Django 2.0.10 on 2019-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sector',
            field=models.CharField(default='', max_length=255, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='Descripción larga'),
        ),
    ]
