# Generated by Django 2.0.10 on 2019-01-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20190128_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='images/category/benefits/', verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_benefits', to='rooms.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Beneficio de Categoria',
                'verbose_name_plural': 'Beneficios de Categoria',
            },
        ),
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='images/category/services/', verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_services', to='rooms.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Servicio de Categoria',
                'verbose_name_plural': 'Servicios de Categoria',
            },
        ),
    ]
