# Generated by Django 2.0.10 on 2019-01-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_categorybenefits_categoryservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybenefits',
            name='image',
            field=models.FileField(upload_to='images/category/benefits/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='categoryservices',
            name='image',
            field=models.FileField(upload_to='images/category/services/', verbose_name='Imagen'),
        ),
    ]
