# Generated by Django 2.0.10 on 2019-02-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20190201_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Habitacion disponible?'),
        ),
    ]
