# Generated by Django 2.0.10 on 2019-03-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_auto_20190306_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryservices',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryservices',
            name='icon_name',
            field=models.CharField(default='', help_text='El nombre del icono de font awesome', max_length=255, verbose_name='Nombre icono'),
            preserve_default=False,
        ),
    ]
