# Generated by Django 2.0.10 on 2019-03-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20190306_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryservices',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='categoryservices',
            name='image',
            field=models.FileField(default='', upload_to='images/category/services/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
