# Generated by Django 2.0.10 on 2019-01-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre usuario')),
                ('profesion', models.CharField(max_length=255, verbose_name='Profesion')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('image', models.ImageField(upload_to='testimonios/', verbose_name='Imagen usuario')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
    ]
