# Generated by Django 2.0.10 on 2019-02-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('option', models.CharField(choices=[('HO', 'Horas'), ('DA', 'Dias'), ('WE', 'Semanas'), ('MO', 'Meses')], max_length=2, verbose_name='Opción de tiempo')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=15, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Servicio',
            },
        ),
        migrations.AddField(
            model_name='optionservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_options', to='services.Services', verbose_name='Servicio'),
        ),
    ]
