# Generated by Django 2.0.10 on 2019-02-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190202_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/services', verbose_name='Imagen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Services', verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.RenameModel(
            old_name='OptionServices',
            new_name='ServicesOption',
        ),
    ]
