# Generated by Django 2.0.10 on 2019-02-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='location',
            field=models.CharField(default='Pereira', max_length=255, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
