# Generated by Django 2.0.10 on 2019-02-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about',
            field=models.TextField(default='', verbose_name='Nuestra Empresa'),
        ),
    ]
