# Generated by Django 2.0.10 on 2019-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0002_companyinfo_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporativeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Valor Corporativo',
            },
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='corporative_values',
        ),
    ]
