# Generated by Django 2.0.10 on 2019-02-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0003_auto_20190224_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporativevalues',
            options={'verbose_name': 'Valor Corporativo', 'verbose_name_plural': 'Valores Corporativo'},
        ),
    ]
